services:
  - type: web
    name: nedzl-market-api
    env: go
    buildCommand: "go build -o main ./..."
    startCommand: "./main"
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
